name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    
    env:
      TAG: ${{ date +%s }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag strapi-demo:$TAG
    - name: Tag
      run: docker tag strapi-demo:$TAG ghcr.io/jaxwood/strapi-demo:$TAG
    - name: Push
      run: docker push ghcr.io/jaxwood/strapi-demo:$TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
