name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    
    env:
      TAG: ${{ github.sha }}
      REGISTRY: ghcr.io
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag strapi-demo:$TAG
    - name: Tag
      run: docker tag strapi-demo:$TAG ghcr.io/jaxwood/strapi-demo:$TAG
    - name: Log in to the Container registry
      uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push
      run: docker push ghcr.io/jaxwood/strapi-demo:$TAG
