name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag strapi-demo:$(date +%s)
    - name: Tag
      run: docker tag strapi-demo:$(date +%s) ghcr.io/jaxwood/strapi-demo:$(date +%s)
    - name: Push
      run: docker push ghcr.io/jaxwood/strapi-demo:$(date +%s)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
